# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 720)
        MainWindow.setMaximumSize(QtCore.QSize(570, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.allcheck = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allcheck.sizePolicy().hasHeightForWidth())
        self.allcheck.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.allcheck.setFont(font)
        self.allcheck.setIconSize(QtCore.QSize(16, 16))
        self.allcheck.setChecked(True)
        self.allcheck.setObjectName("allcheck")
        self.horizontalLayout_3.addWidget(self.allcheck)
        self.randomButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randomButton.sizePolicy().hasHeightForWidth())
        self.randomButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.randomButton.setFont(font)
        self.randomButton.setObjectName("randomButton")
        self.horizontalLayout_3.addWidget(self.randomButton)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.check1 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check1.setFont(font)
        self.check1.setIconSize(QtCore.QSize(16, 16))
        self.check1.setChecked(True)
        self.check1.setObjectName("check1")
        self.verticalLayout.addWidget(self.check1)
        self.check2 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check2.setFont(font)
        self.check2.setIconSize(QtCore.QSize(16, 16))
        self.check2.setChecked(True)
        self.check2.setObjectName("check2")
        self.verticalLayout.addWidget(self.check2)
        self.check3 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check3.setFont(font)
        self.check3.setIconSize(QtCore.QSize(16, 16))
        self.check3.setChecked(True)
        self.check3.setObjectName("check3")
        self.verticalLayout.addWidget(self.check3)
        self.check4 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check4.setFont(font)
        self.check4.setIconSize(QtCore.QSize(16, 16))
        self.check4.setChecked(True)
        self.check4.setObjectName("check4")
        self.verticalLayout.addWidget(self.check4)
        self.check5 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check5.setFont(font)
        self.check5.setIconSize(QtCore.QSize(16, 16))
        self.check5.setChecked(True)
        self.check5.setObjectName("check5")
        self.verticalLayout.addWidget(self.check5)
        self.check6 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check6.setFont(font)
        self.check6.setIconSize(QtCore.QSize(16, 16))
        self.check6.setChecked(True)
        self.check6.setObjectName("check6")
        self.verticalLayout.addWidget(self.check6)
        self.check7 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check7.setFont(font)
        self.check7.setIconSize(QtCore.QSize(16, 16))
        self.check7.setChecked(True)
        self.check7.setObjectName("check7")
        self.verticalLayout.addWidget(self.check7)
        self.check8 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check8.setFont(font)
        self.check8.setIconSize(QtCore.QSize(16, 16))
        self.check8.setChecked(True)
        self.check8.setObjectName("check8")
        self.verticalLayout.addWidget(self.check8)
        self.check9 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check9.setFont(font)
        self.check9.setIconSize(QtCore.QSize(16, 16))
        self.check9.setChecked(True)
        self.check9.setObjectName("check9")
        self.verticalLayout.addWidget(self.check9)
        self.check10 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check10.setFont(font)
        self.check10.setIconSize(QtCore.QSize(16, 16))
        self.check10.setChecked(True)
        self.check10.setObjectName("check10")
        self.verticalLayout.addWidget(self.check10)
        self.check11 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check11.setFont(font)
        self.check11.setIconSize(QtCore.QSize(16, 16))
        self.check11.setChecked(True)
        self.check11.setObjectName("check11")
        self.verticalLayout.addWidget(self.check11)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name1.setFont(font)
        self.name1.setText("")
        self.name1.setObjectName("name1")
        self.verticalLayout_2.addWidget(self.name1)
        self.name2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name2.setFont(font)
        self.name2.setText("")
        self.name2.setObjectName("name2")
        self.verticalLayout_2.addWidget(self.name2)
        self.name3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name3.setFont(font)
        self.name3.setText("")
        self.name3.setObjectName("name3")
        self.verticalLayout_2.addWidget(self.name3)
        self.name4 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name4.setFont(font)
        self.name4.setText("")
        self.name4.setObjectName("name4")
        self.verticalLayout_2.addWidget(self.name4)
        self.name5 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name5.setFont(font)
        self.name5.setText("")
        self.name5.setObjectName("name5")
        self.verticalLayout_2.addWidget(self.name5)
        self.name6 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name6.setFont(font)
        self.name6.setText("")
        self.name6.setObjectName("name6")
        self.verticalLayout_2.addWidget(self.name6)
        self.name7 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name7.setFont(font)
        self.name7.setText("")
        self.name7.setObjectName("name7")
        self.verticalLayout_2.addWidget(self.name7)
        self.name8 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name8.setFont(font)
        self.name8.setText("")
        self.name8.setObjectName("name8")
        self.verticalLayout_2.addWidget(self.name8)
        self.name9 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name9.setFont(font)
        self.name9.setText("")
        self.name9.setObjectName("name9")
        self.verticalLayout_2.addWidget(self.name9)
        self.name10 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name10.setFont(font)
        self.name10.setText("")
        self.name10.setObjectName("name10")
        self.verticalLayout_2.addWidget(self.name10)
        self.name11 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name11.setFont(font)
        self.name11.setText("")
        self.name11.setObjectName("name11")
        self.verticalLayout_2.addWidget(self.name11)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.number1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number1.setFont(font)
        self.number1.setText("")
        self.number1.setObjectName("number1")
        self.verticalLayout_3.addWidget(self.number1)
        self.number2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number2.setFont(font)
        self.number2.setText("")
        self.number2.setObjectName("number2")
        self.verticalLayout_3.addWidget(self.number2)
        self.number3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number3.setFont(font)
        self.number3.setText("")
        self.number3.setObjectName("number3")
        self.verticalLayout_3.addWidget(self.number3)
        self.number4 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number4.setFont(font)
        self.number4.setText("")
        self.number4.setObjectName("number4")
        self.verticalLayout_3.addWidget(self.number4)
        self.number5 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number5.setFont(font)
        self.number5.setText("")
        self.number5.setObjectName("number5")
        self.verticalLayout_3.addWidget(self.number5)
        self.number6 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number6.setFont(font)
        self.number6.setText("")
        self.number6.setObjectName("number6")
        self.verticalLayout_3.addWidget(self.number6)
        self.number7 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number7.setFont(font)
        self.number7.setText("")
        self.number7.setObjectName("number7")
        self.verticalLayout_3.addWidget(self.number7)
        self.number8 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number8.setFont(font)
        self.number8.setText("")
        self.number8.setObjectName("number8")
        self.verticalLayout_3.addWidget(self.number8)
        self.number9 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number9.setFont(font)
        self.number9.setText("")
        self.number9.setObjectName("number9")
        self.verticalLayout_3.addWidget(self.number9)
        self.number10 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number10.setFont(font)
        self.number10.setText("")
        self.number10.setObjectName("number10")
        self.verticalLayout_3.addWidget(self.number10)
        self.number11 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.number11.setFont(font)
        self.number11.setText("")
        self.number11.setObjectName("number11")
        self.verticalLayout_3.addWidget(self.number11)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 11)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "2020届金融管理B班班委随机器"))
        self.allcheck.setText(_translate("MainWindow", "全选"))
        self.randomButton.setText(_translate("MainWindow", "随机生成"))
        self.check1.setText(_translate("MainWindow", "团支书"))
        self.check2.setText(_translate("MainWindow", "正班长"))
        self.check3.setText(_translate("MainWindow", "副班长"))
        self.check4.setText(_translate("MainWindow", "学习委员"))
        self.check5.setText(_translate("MainWindow", "纪律委员"))
        self.check6.setText(_translate("MainWindow", "双创委员"))
        self.check7.setText(_translate("MainWindow", "文体委员"))
        self.check8.setText(_translate("MainWindow", "心理委员"))
        self.check9.setText(_translate("MainWindow", "生活委员"))
        self.check10.setText(_translate("MainWindow", "组织委员"))
        self.check11.setText(_translate("MainWindow", "宣传委员"))
